### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by bearpaw** [jsll/pytorch_6dof-graspnet#1] opened 2020-05-12 16:56 UTC
Hi Jens, thanks for the amazing pytorch code!
After trying the training script, I noticed that the system memory keeps increasing. Just want to check if you have seen the same issue while you trained your model and your ideas about what can cause the memory leak. 

![memory_leak](https://user-images.githubusercontent.com/289501/81732509-74b69b00-9445-11ea-8d54-6682315fda1f.PNG)

**Comment by jsll** [comment] 2020-05-12 19:49
Hi,

I have not seen that issue and I have left my things training for roughly a week. That aside, this is an issue which would need to be solved. Wonder if it is some computational graph that keeps on growing or what the issue is. There might also be some issue with the online_object_renderer.py.

**Comment by bearpaw** [comment] 2020-05-13 19:12
I have verified that the memory leak is caused by the dataloader. I only run the data fetching for a while without any model optimization and see the memory leaking.
![image](https://user-images.githubusercontent.com/289501/81854461-d09b2580-9512-11ea-936d-4d677e86eba9.png)

**Comment by jsll** [comment] 2020-05-14 07:52
@bearpaw I'll close this issue now thanks to your fix

**Closed by jsll** 2020-05-14 07:52 UTC
